### PR TITLE
Add `front` and `back` methods to `doubly::Linked`

### LINKED ISSUE #10: Add peek functions to doubly::Linked
I think the peek functions for nodes will have to go on the `Linked` trait, but can just be written on top of `Linked::next`/`Linked::prev` where the `Linked` type can be borrowed as a `&T`. This will make the cursor implementation (#9) a little easier but probably isn't a strict blocker.

- [ ] `Linked::peek_next` 
- [ ] `Linked::peek_back`

Note that`List` already has peek functions, but they're called `List::front` and `List::back`. Should probably standardise on a naming scheme here.

### PR DESCRIPTION
**Pull request by jdanford**
Closes #10

### CODE REVIEW

**Review by hawkw — CHANGES_REQUESTED** [review]
Hi @jdanford, thanks for the PR!

This is probably my fault, but the `Linked::front`/`Linked::back` methods I had in mind. I realise now that issue #10 doesn't actually make this super clear, but I was hoping for methods on `Linked` to peek at the next and previous elements in the list --- so where `next()` and `prev()` return `Option<&Self>`, `peek_next()` and `peek_back()` would return `Option<&T>` where `Self: AsRef<T>`.

**Comment by hawkw** [comment]
With that said, the functions you've added seem to be implemented correctly, so I'd be happy to merge these changes as well, although I'm not _immediately_ sure what potential use-case there is for them...

**Comment by hawkw** [comment]
(btw, the CI failure is due to issue #14, not your fault. once #16 lands, let's rebase your branch from `master`and it should build again)

**Comment by jdanford** [comment]
Wow I definitely got confused by the names there, my bad! I'll make a new PR that does the right thing.

**Comment by hawkw** [comment]
@jdanford sorry, that's entirely my fault! The issue definitely did not actually describe what we needed.

**Comment by jdanford** [comment]
Okay so I guess this part is confusing me:
> where `next()` and `prev()` return `Option<&Self>`, `peek_next()` and `peek_back()` would return `Option<&T>` where `Self: AsRef<T>`

In what situation would one use `peek_next()` instead of `next()`?

**Comment by hawkw** [comment]
@jdanford if you want to use an intrusive list as a collection of values of type `T`, then the list's nodes (e.g. types implementing `Linked`) must store a `T`. I've been using implementations of `AsRef<T>`/`AsMut<T>` as a way for implementors of node types to signal "hey, my type that implements `Linked` is also a container of `T`s".

In this case, you would use `peek_next()` rather than `next()` when you want to access the _value_ of the next node, rather than the node itself.    

If that's not clear, let me know! I need to document this stuff better anyway.

**Pull request closed without merging**
