### PR TITLE
fix: use hyphens in crate names rather than underscores

### LINKED ISSUE #58: Rename crates with hyphens instead of underscores
From :arrow_right:  To
1. `alarm_base` :arrow_right:  `alarm-base`
2. `intruder_alarm` :arrow_right:  `intruder-alarm`

### PR DESCRIPTION
**Pull request by amanjeev**
closes #58

### CODE REVIEW

**Comment by amanjeev** [comment]
~~Sorry, I forgot CHANGELOG.~~
Nevermind, just remembered that we use clog-cli to auto-generate CHANGELOG.

**Review by hawkw — DISMISSED** [review]
Thanks, this looks good to me! 

Before merging, can we change the description from "refactor: use hyphens in crate names..." to "fix: use hyphens..." (so that it shows up in the changelog), and add a [`BREAKING CHANGE` footer](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.gbbngquhe0qa) to the commit message, since changing package names is technically breaking? Thanks!

**Comment by amanjeev** [comment]
So the latest `nightly` update broke the build. I was confused for a while but realized I needed to `rustup update` on my dev environment. :smiley:.  https://doc.rust-lang.org/alloc/allocator/index.html 

I hope the commit message looks ok to you, now. Please let me know if it needs further explanation or edits.

**Comment by amanjeev** [comment]
I believe I can safely change `alloc::allocator...` to `core::alloc...`.

I made the change. I hope it is ok. Sorry, I am a bit hungover. :face_with_head_bandage: lol

**Review by hawkw — APPROVED** [review]
Thanks, this looks great!

**Comment by amanjeev** [comment]
Thank you!

**Pull request merged**
