### PR TITLE
feat(intruder_alarm::doubly::List): add immutable cursor for doubly-linked lists

### PR DESCRIPTION
**Pull request by hawkw**
Forgot I had this branch open but no PR for it!

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d89c17ddf21f78efb7aafd4fc51c8acf4594fd59
  * Your subject line is longer than 72 characters

 * Commit: b562f93f130c2af53e61e6ae0dae8e1e90553818
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/sos-os/alarm/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d89c17ddf21f78efb7aafd4fc51c8acf4594fd59
  * Your subject line is longer than 72 characters

 * Commit: b562f93f130c2af53e61e6ae0dae8e1e90553818
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/sos-os/alarm/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d89c17ddf21f78efb7aafd4fc51c8acf4594fd59
  * Your subject line is longer than 72 characters

 * Commit: b562f93f130c2af53e61e6ae0dae8e1e90553818
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/sos-os/alarm/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: a5f40df68dc187d8e65fee9ad1cf4a41ab6af056
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 5463e49d71f38706b32072e35b340c1bb86417e1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 14723a6373c7b78dc4beae8af55f22f7e6f8e725
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/sos-os/alarm/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by hawkw** [comment]
I turned off GitCop because it seems to dislike `::`s in scopes. :(

**Pull request merged**
